services:
  - type: worker
    name: loader-start-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python loader_start_worker.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: POLL_SECONDS
        value: "2"

  - type: worker
    name: loader-end-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python loader_end_worker.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: POLL_SECONDS
        value: "2"