services:
  - type: worker
    name: loader-start-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python loader_start_worker.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-d0htaoumcj7s739g9r70-a
          property: connectionString
      - key: POLL_SECONDS
        value: "2"

  - type: worker
    name: loader-end-worker
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python loader_end_worker.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-d0htaoumcj7s739g9r70-a
          property: connectionString
      - key: POLL_SECONDS
        value: "2"