services:
  - type: worker
    name: loader-start-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python loader_start_worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9